export const ADD_NEW_FORM_REQUEST = 'ADD_NEW_FORM_REQUEST';
export const ADD_NEW_FORM_REQUEST_SUCCESS = 'ADD_NEW_FORM_REQUEST_SUCCESS';
export const ADD_NEW_TODO_REQUEST_FAILED = 'ADD_NEW_TODO_REQUEST_FAILED';

export default null;